//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 02:04:08 PM MESZ 
//


package xmlData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="used_capital" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.example.org/CakeEvent}production" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.example.org/CakeEvent}used_ingredient" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="solved" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="solvedAt" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="optimal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profit",
    "usedCapital",
    "production",
    "usedIngredient"
})
@XmlRootElement(name = "solution")
public class Solution {

    protected Double profit;
    @XmlElement(name = "used_capital")
    protected Double usedCapital;
    protected List<Production> production;
    @XmlElement(name = "used_ingredient")
    protected List<UsedIngredient> usedIngredient;
    @XmlAttribute(required = true)
    protected boolean solved;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String solvedAt;
    @XmlAttribute
    protected Boolean optimal;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String status;

    /**
     * Gets the value of the profit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * Sets the value of the profit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProfit(Double value) {
        this.profit = value;
    }

    /**
     * Gets the value of the usedCapital property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUsedCapital() {
        return usedCapital;
    }

    /**
     * Sets the value of the usedCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUsedCapital(Double value) {
        this.usedCapital = value;
    }

    /**
     * Gets the value of the production property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the production property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Production }
     * 
     * 
     */
    public List<Production> getProduction() {
        if (production == null) {
            production = new ArrayList<Production>();
        }
        return this.production;
    }

    /**
     * Gets the value of the usedIngredient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usedIngredient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsedIngredient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsedIngredient }
     * 
     * 
     */
    public List<UsedIngredient> getUsedIngredient() {
        if (usedIngredient == null) {
            usedIngredient = new ArrayList<UsedIngredient>();
        }
        return this.usedIngredient;
    }

    /**
     * Gets the value of the solved property.
     * 
     */
    public boolean isSolved() {
        return solved;
    }

    /**
     * Sets the value of the solved property.
     * 
     */
    public void setSolved(boolean value) {
        this.solved = value;
    }

    /**
     * Gets the value of the solvedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolvedAt() {
        return solvedAt;
    }

    /**
     * Sets the value of the solvedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolvedAt(String value) {
        this.solvedAt = value;
    }

    /**
     * Gets the value of the optimal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptimal() {
        return optimal;
    }

    /**
     * Sets the value of the optimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptimal(Boolean value) {
        this.optimal = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
