//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 02:04:08 PM MESZ 
//


package xmlData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ingredient_id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="amountStock" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="amountBuyed" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="CostBuyed" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="percentOfCostBuyed" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "used_ingredient")
public class UsedIngredient {

    @XmlAttribute(name = "ingredient_id", required = true)
    protected int ingredientId;
    @XmlAttribute(required = true)
    protected double amountStock;
    @XmlAttribute(required = true)
    protected double amountBuyed;
    @XmlAttribute(name = "CostBuyed", required = true)
    protected double costBuyed;
    @XmlAttribute(required = true)
    protected double percentOfCostBuyed;

    /**
     * Gets the value of the ingredientId property.
     * 
     */
    public int getIngredientId() {
        return ingredientId;
    }

    /**
     * Sets the value of the ingredientId property.
     * 
     */
    public void setIngredientId(int value) {
        this.ingredientId = value;
    }

    /**
     * Gets the value of the amountStock property.
     * 
     */
    public double getAmountStock() {
        return amountStock;
    }

    /**
     * Sets the value of the amountStock property.
     * 
     */
    public void setAmountStock(double value) {
        this.amountStock = value;
    }

    /**
     * Gets the value of the amountBuyed property.
     * 
     */
    public double getAmountBuyed() {
        return amountBuyed;
    }

    /**
     * Sets the value of the amountBuyed property.
     * 
     */
    public void setAmountBuyed(double value) {
        this.amountBuyed = value;
    }

    /**
     * Gets the value of the costBuyed property.
     * 
     */
    public double getCostBuyed() {
        return costBuyed;
    }

    /**
     * Sets the value of the costBuyed property.
     * 
     */
    public void setCostBuyed(double value) {
        this.costBuyed = value;
    }

    /**
     * Gets the value of the percentOfCostBuyed property.
     * 
     */
    public double getPercentOfCostBuyed() {
        return percentOfCostBuyed;
    }

    /**
     * Sets the value of the percentOfCostBuyed property.
     * 
     */
    public void setPercentOfCostBuyed(double value) {
        this.percentOfCostBuyed = value;
    }

}
